# uptime.yml — upptime GitHub Actions workflow for tndvnn/adstnd-status repo.
# Secrets required: GH_PAT (repo+workflow scopes), UPTIME_PING_SECRET

name: Upptime
on:
  push:
    branches: [master]
  repository_dispatch:
    types: [trigger]
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  uptime:
    name: Check status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: upptime/uptime-monitor@master
        with:
          command: "update"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          UPTIME_PING_SECRET: ${{ secrets.UPTIME_PING_SECRET }}

  response-time:
    name: Response time check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: upptime/uptime-monitor@master
        with:
          command: "response-time"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          UPTIME_PING_SECRET: ${{ secrets.UPTIME_PING_SECRET }}

  readme:
    name: README
    runs-on: ubuntu-latest
    needs: [uptime, response-time]
    steps:
      - uses: actions/checkout@v3
      - uses: upptime/uptime-monitor@master
        with:
          command: "readme"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

  graphs:
    name: Graphs
    runs-on: ubuntu-latest
    needs: [response-time]
    steps:
      - uses: actions/checkout@v3
      - uses: upptime/uptime-monitor@master
        with:
          command: "graphs"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

  static-site:
    name: Status site
    runs-on: ubuntu-latest
    needs: [readme]
    steps:
      - uses: actions/checkout@v3
      - uses: upptime/uptime-monitor@master
        with:
          command: "site"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
